### PR TITLE
change ideal lunch time to utc

### PR DESCRIPTION
**Pull request by Daniel-Pivonka**

### CODE REVIEW

**Review by nathan-weinberg — CHANGES_REQUESTED** [review]
I think it would make more sense to change our environment to EST

**Comment by Daniel-Pivonka** [comment]
@timflannagan1 is that possible?

**Comment by timflannagan** [comment]
@Daniel-Pivonka all time should be parsed as UTC.

**Review by timflannagan — APPROVED** [review]
lgtm

**Review by nathan-weinberg — APPROVED** [review]

**Pull request merged**
