### PR TITLE
Hardcoded ideal lunch time

### PR DESCRIPTION
**Pull request by nathan-weinberg**

### CODE REVIEW

**Comment by timflannagan** [comment]
🤮

**Comment by Daniel-Pivonka** [comment]
This doesnt seem like a long term solution

**Comment by Daniel-Pivonka** [comment]
lets get @agarcia64 to look at this. the whole ideal lunch time system needs to be gone over to account for day light savings time

**Comment by nathan-weinberg** [comment]
Closing this as it conflicts with #74

**Pull request closed without merging**
