### PR TITLE
Modularize the timbot client.

### PR DESCRIPTION
**Pull request by timflannagan**

### CODE REVIEW

**Review by nathan-weinberg — CHANGES_REQUESTED** [review]
Please squash commits - thanks

**Comment by timflannagan** [comment]
@nathan-weinberg the changes made in each commit are distinct, which warrants an additional commit.

**Comment by Daniel-Pivonka** [comment]
LGTM

**Review by Daniel-Pivonka — APPROVED** [review]

**Comment by nathan-weinberg** [comment]
@timflannagan1 Usually I would require two separate pull requests, but I will make an exception this time. Please be sure to follow best practice in the future.

**Pull request merged**
