### PR TITLE
Adding PEP8 checks to Jenkins

### LINKED ISSUE #39: Add linter to CI

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Fixes #39

### CODE REVIEW

**Comment by Daniel-Pivonka** [comment]
not a fan of pep8 but ill allow it for now

**Comment by nathan-weinberg** [comment]
sir this is an enterprise project we must hold ourselves to industry standard

**Comment by Daniel-Pivonka** [comment]
im a fan of [Black](https://black.readthedocs.io/en/stable/) the uncompromising code formatter

**Comment by timflannagan** [comment]
I'm also a fan of black let's use that instead of this PEP8 garbage

**Review by Daniel-Pivonka — APPROVED** [review]

**Pull request merged**
