### PR TITLE
Moved environmental variables to YAML file for portability

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Signed-off-by: Nathan Weinberg <nathan2@stwmd.net>

### CODE REVIEW

**Comment by Daniel-Pivonka** [comment]
i got this error during testing 

`Traceback (most recent call last):
  File "timbot.py", line 15, in <module>
    slack_token = config['slack_token']
TypeError: string indices must be integers, not str
`

**Comment by timflannagan** [comment]
There's also no requirements.txt lol

**Comment by nathan-weinberg** [comment]
@Dan ack @Tim uh yes there is?

**Comment by Daniel-Pivonka** [comment]
do you plan on perusing this more?

**Comment by nathan-weinberg** [comment]
@Daniel-Pivonka yes if it is still wanted

**Pull request closed without merging**
